### ISSUE TITLE
Type datetime_immutable_no_tz returns current date instead of persited one

### ISSUE THREAD

**Issue by curzio-della-santa** [detailnet/dfw-persistence-module#16]
See [DENNER-2422](https://detailnet.atlassian.net/browse/DENNER-2422) for reference.

![image](https://user-images.githubusercontent.com/7221909/66908862-18ed7600-f00c-11e9-82d8-888ef7ae1125.png)

**Comment by ivan-wolf** [comment]
We will remove the "no_tz" classes soon.
